"""drop redundant index on id pk columns

Revision ID: 285a2502b3e7
Revises: 6f591ee55b0e
Create Date: 2026-06-04 14:54:23.994551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '285a2502b3e7'
down_revision: Union[str, Sequence[str], None] = '6f591ee55b0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ods_id'), table_name='ods')
    op.drop_index(op.f('ix_quality_events_id'), table_name='quality_events')
    op.drop_index(op.f('ix_raw_id'), table_name='raw')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_raw_id'), 'raw', ['id'], unique=False)
    op.create_index(op.f('ix_quality_events_id'), 'quality_events', ['id'], unique=False)
    op.create_index(op.f('ix_ods_id'), 'ods', ['id'], unique=False)
    # ### end Alembic commands ###
