"""initial schema

Revision ID: 6f591ee55b0e
Revises: 
Create Date: 2026-06-04 14:37:11.476430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6f591ee55b0e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('raw_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.String(length=50), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=True),
    sa.Column('ship_mode', sa.String(length=50), nullable=True),
    sa.Column('order_status', sa.String(length=20), nullable=True),
    sa.Column('delivery_date', sa.Date(), nullable=True),
    sa.Column('delivery_days', sa.Integer(), nullable=True),
    sa.Column('returned', sa.Boolean(), nullable=True),
    sa.Column('customer_id', sa.String(length=50), nullable=False),
    sa.Column('customer_name', sa.String(length=100), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('membership_tier', sa.String(length=20), nullable=True),
    sa.Column('registration_date', sa.Date(), nullable=True),
    sa.Column('acquisition_channel', sa.String(length=50), nullable=True),
    sa.Column('newsletter_subscribed', sa.Boolean(), nullable=True),
    sa.Column('preferred_payment_method', sa.String(length=50), nullable=True),
    sa.Column('preferred_device', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('tax_pct', sa.Float(), nullable=True),
    sa.Column('device_used', sa.String(length=50), nullable=True),
    sa.Column('customer_rating', sa.Float(), nullable=True),
    sa.Column('is_repeat_customer', sa.Boolean(), nullable=True),
    sa.Column('items', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('has_clean_error', sa.Boolean(), nullable=False),
    sa.Column('clean_error_message', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('dq_rule_version', sa.String(length=10), nullable=True),
    sa.Column('source_client_id', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ods')),
    sa.UniqueConstraint('raw_id', name=op.f('uq_ods_raw_id'))
    )
    op.create_index(op.f('ix_ods_customer_id'), 'ods', ['customer_id'], unique=False)
    op.create_index(op.f('ix_ods_id'), 'ods', ['id'], unique=False)
    op.create_index(op.f('ix_ods_order_id'), 'ods', ['order_id'], unique=True)
    op.create_index(op.f('ix_ods_source_client_id'), 'ods', ['source_client_id'], unique=False)
    op.create_table('quality_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(length=50), nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('from_state', sa.String(length=30), nullable=True),
    sa.Column('to_state', sa.String(length=30), nullable=False),
    sa.Column('rule_version', sa.String(length=10), nullable=False),
    sa.Column('event_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reason', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quality_events'))
    )
    op.create_index(op.f('ix_quality_events_id'), 'quality_events', ['id'], unique=False)
    op.create_index(op.f('ix_quality_events_order_id'), 'quality_events', ['order_id'], unique=False)
    op.create_index(op.f('ix_quality_events_raw_id'), 'quality_events', ['raw_id'], unique=False)
    op.create_table('raw',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('order_id', sa.String(length=50), nullable=True),
    sa.Column('source_client_id', sa.String(length=50), nullable=True),
    sa.Column('raw_payload', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_raw'))
    )
    op.create_index(op.f('ix_raw_id'), 'raw', ['id'], unique=False)
    op.create_index(op.f('ix_raw_order_id'), 'raw', ['order_id'], unique=False)
    op.create_index(op.f('ix_raw_source_client_id'), 'raw', ['source_client_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raw_source_client_id'), table_name='raw')
    op.drop_index(op.f('ix_raw_order_id'), table_name='raw')
    op.drop_index(op.f('ix_raw_id'), table_name='raw')
    op.drop_table('raw')
    op.drop_index(op.f('ix_quality_events_raw_id'), table_name='quality_events')
    op.drop_index(op.f('ix_quality_events_order_id'), table_name='quality_events')
    op.drop_index(op.f('ix_quality_events_id'), table_name='quality_events')
    op.drop_table('quality_events')
    op.drop_index(op.f('ix_ods_source_client_id'), table_name='ods')
    op.drop_index(op.f('ix_ods_order_id'), table_name='ods')
    op.drop_index(op.f('ix_ods_id'), table_name='ods')
    op.drop_index(op.f('ix_ods_customer_id'), table_name='ods')
    op.drop_table('ods')
    # ### end Alembic commands ###
